### ISSUE TITLE
Add output colours to make it easier to skim

### ISSUE THREAD

**Issue by 0xdevalias** [qqaatw/pytorch-mps-ops-coverage#1]
It would be cool if the output used some colouring/similar to make it easier to skim for support.

A neat example is node.green which shows what versions of Node.js added support for what features, etc:

- https://node.green/
- https://github.com/williamkapke/node-compat-table

**Comment by qqaatw** [comment]
That's a good point, and the example is really cool. I will consider that.

**Comment by qqaatw** [comment]
Colors added!

**Comment by 0xdevalias** [comment]
Awesome, thanks :)
